# 一 异常

## 1.1 概念

异常，就是不正常的意思。在生活中：医生说，你的身体某个部位有异常，该部位和正常相比有点不同，该部位的功能将受影响.在程序中的意思就是:

- 异常：指的是程序在执行过程中，出现的非正常的情况。最終会导致JVM的非正常停止。

在Java等面向对象的编程语言中，异常本身是一个类，产生异常就是创建异常对象并抛出了一个异常对象。Java处理异常的方式是中断处理。
注意：异常指的并不是语法错误语法错了，编译不通过不会产生字节码文件根本不能运行。

## 1.2 异常体系

异常机制其实是帮助我们找到程序中的问题，异常的根类是`java.lang.Throwable`，其下有两个子类：`java.lang.Error`和`java.lang.Exception`，平常所说的异常指`java.lang.Exception`。

<center><a href="https://imgtu.com/i/c8jWa4"><img src="https://z3.ax1x.com/2021/04/07/c8jWa4.png" alt="c8jWa4.png" border="0" /></a></center>

**Throwable体系：**

- **Error：**严重错误Error，无法通过处理的错误，只能事先避免，好比绝症。
- **Exception：**表示异常，异常产生后程序员可以通过代码的方式纠正，使程序继续运行，是必须要处理的。好比感冒、阑尾炎。

**Throwable中常用的方法：**

- `public void printStackTrace()`：打印异常的详细信息。

  包含了异常的类型，异常的原因，还包括异常出现的位置，在开发和调试阶段，都得使用。

- `public String getMessage()`：获取发生异常的原因。

  提示给用户的时候，就是提示错误原因。

- `public String toString()`：获取异常的类型和异常描述信息（不用）。

注意：出现异常时，把异常的简单类名，拷贝到API中去查找产生异常的原因。

## 1.3 异常的分类

**异常（Exception）的分类**：根据在编译时期还是运行时期去检查异常？

- **编译时期异常**：checked异常，在编译时期，就会检查，如果没有处理异常，则编译失败。
- **运行期异常**：runtime异常，在运行时期，检查异常，在编译时期，运行异常不会编译检测（不报错）。

<center><a href="https://imgtu.com/i/c8zQ54"><img src="https://z3.ax1x.com/2021/04/07/c8zQ54.png" alt="c8zQ54.png" border="0" /></a></center>

## 1.4 异常的产生过程解析

先运行下面的程序，程序会产生一个数组索引越界异常`ArrayIndexOfBoundsException`。我们通过图解来解析下异常产生的过程。

```java
// 工具类
public class AraayTools {
    // 对给定的数组通过给定的角标获取元素
    public static int getElement(int[] arr, int index) {
        int element = arr[index];
        return elemet;
    }
}
```

```java
public class ExceptionDemo {
    public static void main(String[] args) {
        int[] arr = {34, 12, 67};
        intnum = ArrayTools.getElement(arr, 3);
        System.out.println("num：" + intnum);
        System.out.printlln("over!");
    }
}
```

图解过程：

<center><a href="https://imgtu.com/i/cGphgs"><img src="https://z3.ax1x.com/2021/04/07/cGphgs.png" alt="cGphgs.png" border="0" /></a></center>



# 二 异常的处理

Java异常处理的五个关键字：**try、catch、finally、throw、throws**

## 2.1 抛出异常throw

在编写程序时，我们必须要考虑程序出现问题的情况。比如，在定义方法时，方法需要接受参数。那么，当调用方法使用接受到的参数时，首先需要先对参数数据进行合法的判断，数据若不合法，就应该告诉调用者，传递合法的数据进来。这时需要使用抛出异常的方式来告诉调用者。
在Java中，提供了一个throw关键字，它用来抛出一个指定的异常对象。那么，抛出一个异常具体如何操作呢?

1. 创建一个异常对象。封装一些提示信息（信息可以自己编写）。

2. 需要将这个异常对象告知给调用者。怎么告知呢？怎么将这个异常对象传递到调用者处呢？通过关键字throw就可以完成。throw 异常对象。

   throw**用在方法内**，用来抛出一个异常对象，将这个异常对象传递到调用者处，并结束当前方法的执行。

**使用格式**：

```java
throw new 异常类名(参数)
```

**注意事项**：

1. `throw`关键字必须写在方法的内部；

2. `throw`关键字后边`new`的对象必须是`Exception`或者`Exception`的子类；

3. `throw`关键字抛出指定的异常对象，我们就必须处理这个异常对象。

   `throw`关键字后边创建的是`RuntimeException`或者是`RuntimeException`的子类对象，我们可以不处理，默认交给JVM处理（打印异常对象，中断程序）。

   `throw`关键字后边创建的是编译异常（写代码的时候报错），我们就必须处理这个异常，要么`throws`，要么`try...catch`。

以后（工作中），首先必须对方法传递过来的参数进行合法性校验。

如果参数不合法，那么必须使用抛出异常的方式，告知方法的调用者，传递的参数有问题。

代码示例：

```java
public class ThrowMain {
    public static void main(String[] args) {
		int[] arr = new int[3];
        int e = getElement(arr, 3);
        System.out.println(e);
    }
    public static int getElement(int[] arr, int index) {
        /*
        	对传递过来的参数数组，进行合法性校验。
        	如果arr的值是null，就抛出空指针异常，告知方法的调用者。
        */
        if (arr == null) {
            throw new NullPointerException("传递的数组为null!");
        }
        /*
        	对传递过来的参数index，进行合法性校验。
        	如果index的范围不在数组的索引范围内，就抛出数组索引越界异常，告知方法的调用者。
        */
        if (index < 0 || index > arr.length - 1) {
            throw new ArrayIndexOfBoundsException("数组索引越界！");
        }
        int ele = arr[index];
        return ele;
    }
}
```

`NullPointerException`和`ArrayIndexOfBoundsException`均为运行期异常，不用处理，默认交给JVM处理。

## 2.2 Objects非空判断

还记得我们学习过一个类Objects吗 ，曾经提到过它由一一些静态的实用方法组成 ，这些方法是`null-save` (空指针安全的)或`null-tolerant` (容忍空指针的)，那么在它的源码中，对对象为`null`的值进行了抛出异常操作。

- `public static <T> requriedNonNull(T obj)`：查看指定引用对象不是null。

查看源码发现这里对为`null`的对象进行了抛出异常操作。

```java
public class <T> T requrieNonNull(T obj) {
    if (obj == null) {
        throw new NullPointerException();
    }
    return obj;
}
```

代码示例：

```java
public class DemoObjects {
    public static void main(String[] args) {
        method(null);
    }
    public static void method(Object obj) {
        /*
        	对传递过来的参数进行合法性判断，判断是否为null。
        	if (obj == null) {
        		throw new NullPointerException("传递的对象的值为null！");
        	}
        */
        /*
        	使用Objects.requireNonNull()对传递过来的参数进行合法性判断。
        	Objects.requireNonNull(obj);
        	Objects.requireNonNull(obj, "传递的对象的值为null！");
        */
    }
}
```

## 2.3 声明异常throws

**声明异常**：将问题标识出来，报告给调用者。如果方法内通过`throw`抛出了编译时异常，而没有捕获处理（稍后讲解该方式）, 那么必须通过`throws`进行声明，让调用者去处理。
关键字**`throws`**运用于方法声明之上，用于表示当前方法不处理异常，而是提醒该方法的调用者来处理异常（抛出异常）。
**声明异常格式**：

```java
修饰符 返回值类型 方法名(参数) throws 异常类名1, 异常类名2, ... {
    
}
```

**注意事项**：

1. `throws`关键字必须写在方法声明处；

2. `throws`关键字后边声明的异常必须是`Exception`或者是`Exception`的子类；

3. 方法的内部如果抛出了多个异常对象，那么`throws`后边也必须声明多个异常；

   如果抛出的多个异常对象有子父类关系，那么直接声明父类异常即可。

4. 调用了一个声明抛出异常的方法，就必须处理声明的异常。

   要么继续使用`throws`声明抛出，交给方法的调用者处理，最终交给JVM。

   要么`try...catch`自己处理异常。

代码示例：

```java
public class ThrowsDemo {
    public static void main(String[] args) throws FileNotFoundException, IOException {
        read("a.txt");
    }
    public static void read(String path) throws FileNotFoundException, IOException {
    	/*
    	如果定义功能时有问题发生需要报告给调用者，可以通过在方法上使用throws关键字进行声明。
    	*/
        if (!path.equals("a.txt")) {
            /*
            	如果不是a.txt这个文件，认为该文件不存在，是一个错误，也就是异常，抛出！
            */
            throw new FileNotFoundException("文件不存在！");
        }
        if (!path.endsWith(".txt")) {
            /*
            	如果文件名后缀不是.txt，就抛出异常。
            */
            throw new IOException("文件后缀名不对！");
        }
    }
}
```

`FileNotFoundException`是编译异常，就必须处理，要么`throws`，要么`try...catch`。

`FileNotFoundException`是`IOException`的子类，所以仅声明`IOException`即可。

## 2.4 捕获异常try-catch

如果异常出现的话，会立刻终止程序，所以我们得处理异常：

1. 该方法不处理，而是声明抛出，由该方法的调用者来处理(`throws`)。
2. 在方法中使用`try-catch`的语句块来处理异常。

**`try-catch`**的方式就是捕获异常。

- **捕获异常**：Java中对异常有针对性的语句进行捕获，可以对出现的异常进行指定方式的处理。

**使用格式**：

```java
try {
    撰写可能会出现异常的代码;
} catch (异常类型 e) {
    处理异常的代码;
    // 记录日志、打印异常信息、继续抛出异常
} catch (异常类型 e) {
    处理异常的代码;
}
// catch可以有多个！！！
```

**注意事项**：

1. `try`中可能会抛出多个异常对象，那么就可以使用多个`catch`来处理这些异常对象；

2. 如果`try`中产生了异常，那么就会执行`catch`中的异常处理逻辑，执行完毕`catch`中的处理逻辑，继续执行`try...catch`之后的代码；

   如果`try`中没有产生异常，那么就不会执行`catch`中异常的处理逻辑，执行完`try`中的代码，继续执行`try...catch`之后的代码。

代码示例：

```java
public class TryCatchDemo {
    public static void main(String[] args) {
        try {
            // 可能产生异常的代码
            read("a.txt");
        } catch (IOException e) {
            // try中抛出什么异常对象，catch就定义什么异常变量，用来接收这个异常对象。
            System.out.println("传递的文件的后缀不是.txt！");
        }
        System.out.println("后续代码！");
    }
    public static void read(String path) throws IOException {
        if (!path.endsWith(".txt")) {
            /*
            	如果文件名后缀不是.txt，就抛出异常。
            */
            throw new IOException("文件后缀名不对！");
        }
        System.out.println("路径没有问题，读取文件！");
    }
}
```



`Throwable`类中定义了一些查看方法：

- `public String getMessage()`：获取异常的描述信息，原因（提示给用户的时候，就提示错误原因）。

- `public String toString()`：获取异常的类型和异常描述信息（不用）。

- `public void printStackTrace()`：打印异常的跟踪栈信息并输出到控制台。

  包含了异常的类型，异常的原因，还包括异常出现的位置，在开发和调试阶段，都得使用`printStackTrace()`。

在开发中也可以在`catch`将编译期异常转换成运行期异常处理。

代码示例：

```java
public class TryCatchDemo {
    public static void main(String[] args) {
        try {
            read("a.txt");
        } catch (IOException e) {
            System.out.println(e.getMessage());
            // 输出：文件的后缀名不对
            System.out.println(e.toString());
            System.out.println(e);
            // 输出：java.lang.IOException：文件的后缀名不对
            e.printStackTrace();
            /*
            	输出：
            	java.io.IOException：文件的后缀名不对
            		at XXX.XXX.XXX.Exception.TryCatchDemo.read(TryCatchDemo.java:xx)
            		at XXX.XXX.XXX.Exception.TryCatchDemo.main(TryCatchDemo.java:xx)
            */
        }
        System.out.println("后续代码！");
    }
    public static void read(String path) throws IOException {
        if (!path.endsWith(".txt")) {
            throw new IOException("文件后缀名不对！");
        }
        System.out.println("路径没有问题，读取文件！");
    }
}
```

## 2.4 finally代码块

**finally**：有一些特定的代码无论异常是否发生，都需要执行。另外，因为异常会引发程序跳转。导致有些语句执行不到。而`finally`就是解决这个问题的，在`finally`代码块中存放的代码都是一定会被执行的。
什么时候的代码必须最终执行?
当我们在`try`语句块中打开了一些物理资源(磁盘文件、网络连接、数据库连接等，我们都得在使用完之后，最终关闭打开的资源。
**格式**：

```java
try {
    可能会产生异常的代码;
} catch (异常类型 e) {
	异常处理;
} finally {
    无论是否产生异常，都要执行的代码;
}
```

**注意事项**：

1. `finally`不能单独使用，必须和`try`一起使用。
2. `finally`一般用于资源释放（资源回收），无论程序是否出现异常，最后都要资源释放(IO)。

代码示例：

```java
public class TryCatchDemo {
    public static void main(String[] args) {
		try {
            read("a.txt");
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            System.out.println("资源释放！");
        }
    }
    public static void read(String path) throws IOException {
        if (!path.endsWith(".txt")) {
            throw new IOException("文件后缀名不对！");
        }
        System.out.println("路径没有问题，读取文件！");
    }
}
```

## 2.5 异常注意事项

- 多个异常使用捕获又该如何处理呢？
  1. 多个异常分别处理；
  2. 多个异常一次捕获，多次处理；
  3. 多个异常一次捕获，一次处理。

一般使用一次捕获多次处理方式，格式如下：

```java
try {
    可能会出现异常的代码;
} catch (异常类型A e) {
    处理A类异常代码; // 记录日志、打印异常信息、继续抛出异常
} catch (异常类型B e) {
    处理B类异常代码; // 记录日志、打印异常信息、继续抛出异常
}
```

**注意**：这种异常处理方式，要求多个`catch`中的异常不能相同，并且若`catch`中的多个异常之间有子父类异常的关系，那么子类异常要求在上面的`catch`处理，父类异常在下面的`catch`处理。

<center><a href="https://imgtu.com/i/cGGvkT"><img src="https://z3.ax1x.com/2021/04/07/cGGvkT.png" alt="cGGvkT.png" border="0" /></a></center>

- 运行时异常被抛出可以不处理，即不捕获也不声明抛出。
- 如果`finally`有`return`语句，永远返回`finally`中的结果，要避免这种情况。

代码示例：

```java
public class DemoException {
    public static void main(String[] args) {
        int a = getA();
        System.out.println(a); // 输出：100
    }
    public static int getA() {
        int a = 10;
        try {
            return a;
        } catch (Exception e) {
            System.out.println(e);
        } finally {
            int a = 100;
            return a;
        }
    }
}
```

- 如果父类抛出多个异常，子类覆盖父类方法时，只能抛出相同的异常或是他的子集。

- 父类方法没有抛出异常，子类覆盖父类该方法时也不可抛出异常。此时子类产生该异常，只能捕获处理，不能声明抛出。

  总结：**父类异常是什么样，子类异常就什么样！！！**

代码示例：

```java
public class Fu {
    public void show01() throws NullPointerException, ClassCastException {}
    public void show02() throws IndexOutOfBoundsException {}
    public void show03() throws IndexOutOfBoundsException {}
    public void show04() {}
}
class Zi extends Fu {
    // 子类重写父类方法时，抛出和父类相同的异常。
    public void show01() throws NullPointerException, ClassCastException {}
    // 子类重写父类方法时，抛出父类异常的子类。
    public void show02() throws ArrayIndexOutOfBoundsException {}
    // 子类重写父类方法时，不抛出异常
    public void show03() {}
    // 子类方法没有抛出异常，子类重写该方法时，也不可抛出异常。产生异常后，只能捕获处理，不能声明抛出
    public void show04() {
        try {
            throw new Exception("编译器异常");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

- 在`try-catch`后可以追加`finally`代码块，其中的代码一定会被执行，通常用于资源回收。



# 三 自定义异常

## 3.1 概述

**为什么需要自定义异常类**：
我们说了Java中不同的异常类分别表示着某一种具体的异常情况，那么在开发中总是有些异常情况是SUN没有定义好的，此时我们根据自己业务的异常情况来定义异常类。例如年龄负数问题，考试成绩负数问题等等。
在上述代码中，发现这些异常都是JDK内部定义好的，但是实际开发中也会出现很多异常，这些异常很可能在JDK中没有定义过，例如年龄负数问题，考试成绩负数问题，那么能不能自己定义异常呢?

**什么是自定义异常类**:
在开发中根据自己业务的异常情况来定义异常类。
自定义一个业务逻辑异常：`RegisterException`，一个注册异常类。

**异常类如何定义**:

1. 自定义一个编译期异常：自定义类并继承于`java.lang.Exception`。
2. 自定义一个运行时期的异常类：自定义类并继承于`java.lang.RuntimeException`。

**格式**：

```java
public class XXXException extends Exception | RuntimeException {
    添加一个空参数的构造方法;
    添加一个带异常信息的构造方法;
}
```

**注意事项**：

1. 自定义异常类一般都是以`Exception`结尾，说明该类是一个异常类。

2. 自定义异常类，必须的继承`Exception`或者`RuntimeException`

   继承`Exception`：那么自定义的异常类就是一个编译期异常，如果方法内部抛出了编译器异常，就必须处理这个异常，要么`throws`，要么`try-catch`。

   继承`RuntimeException`：那么自定义的异常类就是一个运行期异常，无需处理，交给虚拟机处理（中断处理）。

代码示例：

```java
public class RegisterException extends {
    // 添加一个空参数的构造方法
    public RegisterException() {
     	super();   
    }
    // 添加一个带异常信息的构造方法
    public RegisterException(String s) {
        super(s);
    }
}
```

查看源码发现，所有的异常类都会有一个带异常信息的构造方法，方法内部会调用父类带异常信息的构造方法，让父类来处理这个异常信息。

## 3.2 自定义异常的练习

要求：模拟注册操作，如果用户名已存在，则抛出异常并提示：亲，该用户名已经被注册。

分析：

 1. 使用数组（数据库）保存已经注册过的用户名。

 2. 使用`Scanner()`获取用户输入的注册的用户名。（前端、页面）

 3. 定义一个方法，对用户输入的用户名进行判断。

    遍历已经注册过的用户名数组，获取每一个用户名。（数据库：查询操作）

    使用获取到的**用户名**和用户**输入的用户名**进行比较。

    ​		**true**：用户名已经存在，抛出`RegisterException`异常，告知用户"亲，该用户名已经被注册。"

    ​		**false**：继续遍历比较。

    如果遍历结束了，还没有找到重复的用户名，提示用户""

首先定义一个登录异常类`RegisterException`：

```java
// 业务逻辑异常
public class RegisterException extends Exception {
    public RegisterException () {
        super();
    }
    public RegisterException (String message) {
        super(message);
    }
}
```

